language: python
python:
  - 2.7
cache:
  directories:
    - eggs
install:
  - python bootstrap.py --setuptools-version=8.3
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -Nq -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
