language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout -Nq -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test

notifications:
  email:
    - gil.cano@gmail.com
