language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout annotate
  - bin/buildout
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
after_failure:
  - bin/flake8 --version
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
notifications:
  email:
    - informatica.academica@matem.unam.mx
