sudo: false
language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/buildout-cache
    - $HOME/parts/node
install:
  - python bootstrap.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout -Nq -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install coverage==3.7 coveralls
  - coveralls
after_failure:
  - bin/flake8 --version
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
notifications:
  email:
    - gil.cano@gmail.com

env:
  matrix:
    - CONF=travis.cfg
    - CONF=extras.cfg EXTRAS_INSTALLED=true
matrix:
  allow_failures:
    - python: 3.4
      env: CONF=extras.cfg EXTRAS_INSTALLED=true
install:
  - python bootstrap-buildout.py --setuptools-version=18.5
  - bin/buildout -c $CONF annotate
  - bin/buildout -N -t 3 -c $CONF