# -*- coding: utf-8 -*-

from Products.ATCountryWidget.config import COUNTRIES
from Products.Archetypes.atapi import DisplayList
from matem.solicitudes import solicitudesMessageFactory as _
from plone.i18n.normalizer import idnormalizer as idn
from zope.component.hooks import getSite


ADD_CONTENT_PERMISSION = {
    "Solicitud": "Solicitud: Add Solicitud",
    "SolicitudBecario": "SolicitudBecario: Add SolicitudBecario",
    "SolicitudVisitante": "SolicitudVisitante: Add SolicitudVisitante",
    "SolicitudFolder": "SolicitudFolder: Add SolicitudFolder",
    'SolicitudInstitucional': 'matem.solicitudes: Add Solicitud Institucional',
}

GLOBALS = globals()
PROJECTNAME = "matem.solicitudes"

AREAS_INVESTIGACION = DisplayList((
    ('00-xx', '00-xx General'),
    ('01-xx', '01-xx History and biography'),
    ('03-xx', '03-xx Mathematical logic and foundations'),
    ('05-xx', '05-xx Combinatorics'),
    ('06-xx', '06-xx Order, lattices, ordered algebraic structures'),
    ('08-xx', '08-xx General algebraic systems'),
    ('11-xx', '11-xx Number theory'),
    ('12-xx', '12-xx Field theory and polynomials'),
    ('13-xx', '13-xx Commutative rings and algebras'),
    ('14-xx', '14-xx Algebraic geometry'),
    ('15-xx', '15-xx Linear and multilinear algebra; matrix theory'),
    ('16-xx', '16-xx Associative rings and algebras'),
    ('17-xx', '17-xx Nonassociative rings and algebras'),
    ('18-xx', '18-xx Category theory; homological algebra'),
    ('19-xx', '19-xx $K$-theory'),
    ('20-xx', '20-xx Group theory and generalizations'),
    ('22-xx', '22-xx Topological groups, Lie groups'),
    ('26-xx', '26-xx Real functions'),
    ('28-xx', '28-xx Measure and integration'),
    ('30-xx', '30-xx Functions of a complex variable'),
    ('31-xx', '31-xx Potential theory'),
    ('32-xx', '32-xx Several complex variables and analytic spaces'),
    ('33-xx', '33-xx Special functions'),
    ('34-xx', '34-xx Ordinary differential equations'),
    ('35-xx', '35-xx Partial differential equations'),
    ('37-xx', '37-xx Dynamical systems and ergodic theory'),
    ('39-xx', '39-xx Difference and functional equations'),
    ('40-xx', '40-xx Sequences, series, summability'),
    ('41-xx', '41-xx Approximations and expansions'),
    ('42-xx', '42-xx Fourier analysis'),
    ('43-xx', '43-xx Abstract harmonic analysis'),
    ('44-xx', '44-xx Integral transforms, operational calculus'),
    ('45-xx', '45-xx Integral equations'),
    ('46-xx', '46-xx Functional analysis'),
    ('47-xx', '47-xx Operator theory'),
    ('49-xx', '49-xx Calculus of variations and optimal control; optimization'),
    ('51-xx', '51-xx Geometry'),
    ('52-xx', '52-xx Convex and discrete geometry'),
    ('53-xx', '53-xx Differential geometry'),
    ('54-xx', '54-xx General topology'),
    ('55-xx', '55-xx Algebraic topology'),
    ('57-xx', '57-xx Manifolds and cell complexes'),
    ('58-xx', '58-xx Global analysis, analysis on manifolds'),
    ('60-xx', '60-xx Probability theory and stochastic processes'),
    ('62-xx', '62-xx Statistics'),
    ('65-xx', '65-xx Numerical analysis'),
    ('68-xx', '68-xx Computer science'),
    ('70-xx', '70-xx Mechanics of particles and systems'),
    ('74-xx', '74-xx Mechanics of deformable solids'),
    ('76-xx', '76-xx Fluid mechanics'),
    ('78-xx', '78-xx Optics, electromagnetic theory'),
    ('80-xx', '80-xx Classical thermodynamics, heat transfer'),
    ('81-xx', '81-xx Quantum theory'),
    ('82-xx', '82-xx Statistical mechanics, structure of matter'),
    ('83-xx', '83-xx Relativity and gravitational theory'),
    ('85-xx', '85-xx Astronomy and astrophysics'),
    ('86-xx', '86-xx Geophysics'),
    ('90-xx', '90-xx Operations research, mathematical programming'),
    ('91-xx', '91-xx Game theory, economics, social and behavioral sciences'),
    ('92-xx', '92-xx Biology and other natural sciences'),
    ('93-xx', '93-xx Systems theory; control'),
    ('94-xx', '94-xx Information and communication, circuits'),
    ('97-xx', '97-xx Mathematics education'),
))

DICCIONARIO_AREAS_EN = {
    "00-xx": "00-xx General",
    "01-xx": "01-xx History and biography",
    "03-xx": "03-xx Mathematical logic and foundations",
    "05-xx": "05-xx Combinatorics",
    "06-xx": "06-xx Order, lattices, ordered algebraic structures",
    "08-xx": "08-xx General algebraic systems",
    "11-xx": "11-xx Number theory",
    "12-xx": "12-xx Field theory and polynomials",
    "13-xx": "13-xx Commutative rings and algebras",
    "14-xx": "14-xx Algebraic geometry",
    "15-xx": "15-xx Linear and multilinear algebra; matrix theory",
    "16-xx": "16-xx Associative rings and algebras",
    "17-xx": "17-xx Nonassociative rings and algebras",
    "18-xx": "18-xx Category theory; homological algebra",
    "19-xx": "19-xx $K$-theory",
    "20-xx": "20-xx Group theory and generalizations",
    "22-xx": "22-xx Topological groups, Lie groups",
    "26-xx": "26-xx Real functions",
    "28-xx": "28-xx Measure and integration",
    "30-xx": "30-xx Functions of a complex variable",
    "31-xx": "31-xx Potential theory",
    "32-xx": "32-xx Several complex variables and analytic spaces",
    "33-xx": "33-xx Special functions",
    "34-xx": "34-xx Ordinary differential equations",
    "35-xx": "35-xx Partial differential equations",
    "37-xx": "37-xx Dynamical systems and ergodic theory",
    "39-xx": "39-xx Difference and functional equations",
    "40-xx": "40-xx Sequences, series, summability",
    "41-xx": "41-xx Approximations and expansions",
    "42-xx": "42-xx Fourier analysis",
    "43-xx": "43-xx Abstract harmonic analysis",
    "44-xx": "44-xx Integral transforms, operational calculus",
    "45-xx": "45-xx Integral equations",
    "46-xx": "46-xx Functional analysis",
    "47-xx": "47-xx Operator theory",
    "49-xx": "49-xx Calculus of variations and optimal control; optimizatión",
    "51-xx": "51-xx Geometry",
    "52-xx": "52-xx Convex and discrete geometry",
    "53-xx": "53-xx Differential geometry",
    "54-xx": "54-xx General topology",
    "55-xx": "55-xx Algebraic topology",
    "57-xx": "57-xx Manifolds and cell complexes",
    "58-xx": "58-xx Global analysis, analysis on manifolds",
    "60-xx": "60-xx Probability theory and stochastic processes",
    "62-xx": "62-xx Statistics",
    "65-xx": "65-xx Numerical analysis",
    "68-xx": "68-xx Computer science",
    "70-xx": "70-xx Mechanics of particles and systems",
    "74-xx": "74-xx Mechanics of deformable solids",
    "76-xx": "76-xx Fluid mechanics",
    "78-xx": "78-xx Optics, electromagnetic theory",
    "80-xx": "80-xx Classical thermodynamics, heat transfer",
    "81-xx": "81-xx Quantum theory",
    "82-xx": "82-xx Statistical mechanics, structure of matter",
    "83-xx": "83-xx Relativity and gravitational theory",
    "85-xx": "85-xx Astronomy and astrophysics",
    "86-xx": "86-xx Geophysics",
    "90-xx": "90-xx Operations research, mathematical programming",
    "91-xx": "91-xx Game theory, economics, social and behavioral sciences",
    "92-xx": "92-xx Biology and other natural sciences",
    "93-xx": "93-xx Systems theory; control",
    "94-xx": "94-xx Information and communication, circuits",
    "97-xx": "97-xx Mathematics education",
}

DICCIONARIO_AREAS = {
    "00-xx": "00-xx General",
    "01-xx": "01-xx Historia y biografía",
    "03-xx": "03-xx Lógica matemática y fundamentos",
    "05-xx": "05-xx Combinatoria",
    "06-xx": "06-xx Órdenes, látices, estructuras algebraicas ordenadas",
    "08-xx": "08-xx Sistemas algebraicos generales",
    "11-xx": "11-xx Teoría de numeros",
    "12-xx": "12-xx Teoría de campos y polinomios",
    "13-xx": "13-xx Anillos conmutativos y álgebras",
    "14-xx": "14-xx Geometría algebraica",
    "15-xx": "15-xx Álgebra lineal y multilineal; teoría de matrices",
    "16-xx": "16-xx Anillos asociativos y álgebras",
    "17-xx": "17-xx Anillos y álgebras no asociativas",
    "18-xx": "18-xx Teoría de categorías; álgebra homológica",
    "19-xx": "19-xx $K$-teoría",
    "20-xx": "20-xx Teoría de grupos y generalizaciones",
    "22-xx": "22-xx Grupos topológicos, grupos de Lie",
    "26-xx": "26-xx Funciones reales",
    "28-xx": "28-xx Medida e integración",
    "30-xx": "30-xx Funciones de variable compleja",
    "31-xx": "31-xx Teoría de potencial",
    "32-xx": "32-xx Varias variables complejas y espacios analíticos",
    "33-xx": "33-xx Funciones especiales",
    "34-xx": "34-xx Ecuaciones diferenciales ordinarias",
    "35-xx": "35-xx Ecuaciones diferenciales parciales",
    "37-xx": "37-xx Sistemas dinámicos y teoría ergódica",
    "39-xx": "39-xx Ecuaciones en diferencias y funcionales",
    "40-xx": "40-xx Secuencias, series, sumabilidad",
    "41-xx": "41-xx Aproximaciones y expansiones",
    "42-xx": "42-xx Análisis de Fourier",
    "43-xx": "43-xx Análisis armónico abstracto",
    "44-xx": "44-xx Transformadas enteras, cálculo operacional",
    "45-xx": "45-xx Ecuaciones enteras",
    "46-xx": "46-xx Análisis funcional",
    "47-xx": "47-xx Teoría de operadores",
    "49-xx": "49-xx Cálculo de variaciones y control óptimo; optimizacion",
    "51-xx": "51-xx Geometría",
    "52-xx": "52-xx Geometría convexa y discreta",
    "53-xx": "53-xx Geometría diferencial",
    "54-xx": "54-xx Topología general",
    "55-xx": "55-xx Topología algebraica",
    "57-xx": "57-xx Variedades y complejos de celdas",
    "58-xx": "58-xx Análisis global, análisis de variedades",
    "60-xx": "60-xx Teoría de probabilidad y procesos estocásticos",
    "62-xx": "62-xx Estadística",
    "65-xx": "65-xx Análisis numérico",
    "68-xx": "68-xx Ciencias de la computación",
    "70-xx": "70-xx Mecánica de partículas y sistemas",
    "74-xx": "74-xx Mecánica de sólidos deformables",
    "76-xx": "76-xx Mecánica de fluidos",
    "78-xx": "78-xx Óptica, teoría electromagnética",
    "80-xx": "80-xx Termodinámica clásica, transferencia de calor",
    "81-xx": "81-xx Teoría cuántica",
    "82-xx": "82-xx Mecánica estadística, estructura de la materia",
    "83-xx": "83-xx Teoría de la relatividad y gravitacional",
    "85-xx": "85-xx Astronomía y astrofísica",
    "86-xx": "86-xx Geofísica",
    "90-xx": "90-xx Investigación de operaciones, programación matemática",
    "91-xx": "91-xx Teoría de juegos, economía, ciencias sociales y de comportamiento",
    "92-xx": "92-xx Biología y otras ciencias naturales",
    "93-xx": "93-xx Teoría de sistemas; control",
    "94-xx": "94-xx Información y comunicación, circuitos",
    "97-xx": "97-xx Educación matemática",
}

DICCIONARIO_TIPO_TRANSPORTE_EN = {
    "auto": _(u'Car'),
    "autobus": _(u'Bus'),
    "avion": _(u'Airplane'),
}

DICCIONARIO_TIPO_TRANSPORTE = {
    "auto": "Auto",
    "autobus": "Autobus",
    "avion": "Avion",
}

NIVEL = DisplayList((
    ('Doctorado', _(u'PHD')),
    ('Maestria', _(u'Mastery')),
    ('Licenciatura', _(u'Undergraduate')),
))

SEDE = DisplayList((
    ('cu', 'C.U.'),
    ('matcuer', 'Cuernavaca'),
    ('juriquilla', 'Juriquilla'),
    ('matmor', 'Morelia'),
    ('oaxaca', 'Oaxaca'),
))

EVENTOS_INSTITUCIONALES = ((
    ('malaga', 'Malaga'),
))


# TODO change location of this vocabulary
def getCountriesVocabulary(self):
    translation_service = getSite().translation_service
    sorted_list = [x for x in COUNTRIES.iteritems()]
    sorted_list.append(('', ''))
    spanish_list = [(x[0], translation_service.translate(x[1], domain="plone", target_language="es")) for x in sorted_list]
    spanish_list.sort(key=lambda x: idn.normalize(x[1]))
    return DisplayList(spanish_list)
